kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: argo
  name: pod-patch-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
